# ==========================================
# ITACHI - KITTY TERMINAL
# ==========================================

font_family      JetBrains Mono
font_size        12.0

background       #080808
foreground       #e6e6e6

cursor           #ff1a1a
cursor_text_color #080808

selection_background #3a0808
selection_foreground #ffffff

color0  #080808
color1  #ff1a1a
color2  #7a9a5b
color3  #c47f3c
color4  #4d6fa8
color5  #9b4d8b
color6  #4f8f8f
color7  #bdbdbd

color8  #333333
color9  #ff3333
color10 #8fb36a
color11 #d99a52
color12 #668dcc
color13 #b86aa8
color14 #65aaaa
color15 #ffffff

window_padding_width 12

background_opacity 0.92

enable_audio_bell no

confirm_os_window_close 0